const products = [
      {
        id:'5',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 329,
        quantity: 5,
        photo: 'e2.png',
        shipping: 'yes',
      },
      {
        id:'6',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 32,
        quantity: 5,
        photo: 'e1.png',
        shipping: 'yes',
      },
      {
        id:'7',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 29,
        quantity: 5,
        photo: 'l3.png',
        shipping: 'yes',
      },
      {
        id:'8',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 529,
        quantity: 5,
        photo: 'l2.png',
        shipping: 'yes',
      },
      {
        id: '1',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 13,
        quantity: 5,
        photo: 'a1.png',
        shipping: 'Yes',
      },
      {
        id:'2',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 45,
        quantity: 5,
        photo: 'a2.png',
        shipping: 'No',
      },
      {
        id:'3',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 329,
        quantity: 5,
        photo: 'a3.png',
        shipping: 'yes',
      },
      {
        id:'4',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 329,
        quantity: 5,
        photo: 'e3.png',
        shipping: 'yes',
      },
      {
        id:'9',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 329,
        quantity: 5,
        photo: 'l1.png',
        shipping: 'yes',
      },
    
      {
        id: '19',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 45,
        quantity: 5,
        photo: 'm1.png',
        shipping: 'Yes',
      },
      {
        id:'20',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 45,
        quantity: 5,
        photo: 'm2.png',
        shipping: 'No',
      },
      {
        id:'21',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 379,
        quantity: 5,
        photo: 'm3.png',
        shipping: 'yes',
      },
      {
        id:'22',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 177,
        quantity: 5,
        photo: 's3.png',
        shipping: 'yes',
      },
      {
        id:'23',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 100,
        quantity: 5,
        photo: 's2.png',
        shipping: 'yes',
      },
      {
        id:'24',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 100,
        quantity: 5,
        photo: 's1.png',
        shipping: 'yes',
      },
      {
        id:'25',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 200,
        quantity: 5,
        photo: 'w3.png',
        shipping: 'yes',
      },
      {
        id:'26',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 230,
        quantity: 5,
        photo: 'w2.png',
        shipping: 'yes',
      },
      {
        id:'27',
        name: 'watch',
        slug: 'watch',
        description: 'this is a febric watch',
        price: 238,
        quantity: 5,
        photo: 'w1.png',
        shipping: 'yes',
      },
]

export default products;